# Logistic Regression

## One Variable

In [1]:
import pandas as pd
import numpy as np

C:\Users\manis\AppData\Local\Temp\ipykernel_1012\2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = [
    [35.0, 0.0],
    [42.0, 0.0],
    [50.0, 0.0],
    [60.0, 0.0],
    [67.0, 1.0],
    [75.0, 1.0],
    [80.0, 1.0],
    [90.0, 1.0],
    [95.0, 1.0],
    [100.0, 1.0],
    [110.0, 1.0],
    [120.0, 1.0],
    [130.0, 1.0],
    [140.0, 1.0],
    [150.0, 1.0],
    [160.0, 1.0],
    [175.0, 1.0],
    [190.0, 1.0],
    [210.0, 1.0],
    [230.0, 1.0]
]


In [3]:
df = pd.DataFrame(df, columns=['exam_score', 'admitted'])

In [4]:
print(df.head())

   exam_score  admitted
0        35.0       0.0
1        42.0       0.0
2        50.0       0.0
3        60.0       0.0
4        67.0       1.0


In [5]:
print(df.shape)

(20, 2)


In [6]:
X = df['exam_score']
y = df['admitted']

In [7]:
mean_val = X.mean()
std_val = X.std(ddof=0)
min_val = X.min()
max_val = X.max()

print(f"{mean_val:.2f} {std_val:.2f} {min_val:.2f} {max_val:.2f}")

115.45 55.22 35.00 230.00


### Logistic Functions

In [8]:
alpha = 0.01
epochs = 1000
theta0 = 0.0
theta1 = 0.0
n = len(df)

In [9]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [10]:
for i in range(epochs):
    z = theta0 + (theta1 * X)
    y_cap = sigmoid(z)

    grad0 = np.mean(y_cap - y)
    grad1 = np.mean((y_cap - y) * X)

    theta0 -= alpha * grad0
    theta1 -= alpha * grad1

In [11]:
print(f"{theta0:.2f} {theta1:.2f}")

-1.18 0.19


In [12]:
def calculate_loss(y, y_cap):
    ep = 1e-8
    return -np.mean((y * np.log(y_cap + ep)) + ((1 - y) * np.log(1 - y_cap + ep)))

In [13]:
z = theta0 + (theta1 * X)
ypred = sigmoid(z)
loss = calculate_loss(y, ypred)

In [14]:
print(f"{loss:.2f}")

1.55


In [15]:
def predict(val):
    z = theta0 + (theta1 * val)
    return sigmoid(z)

In [16]:
print(f"{predict(65):.2f}")
print(f"{predict(155):.2f}")

1.00
1.00


## Multi Variable

In [17]:
import pandas as pd
import numpy as np

In [45]:
df = [
    [35, 40, 5, 0],
    [42, 50, 6, 0],
    [50, 52, 7, 0],
    [60, 65, 8, 0],
    [67, 70, 9, 1],
    [75, 78, 10, 1],
    [80, 85, 12, 1],
    [90, 88, 14, 1],
    [95, 90, 15, 1],
    [100, 92, 16, 1],
    [110, 100, 17, 1],
    [120, 105, 18, 1],
    [130, 110, 19, 1],
    [140, 115, 20, 1],
    [150, 118, 22, 1],
    [160, 120, 24, 1],
    [175, 125, 25, 1],
    [190, 128, 26, 1],
    [210, 130, 28, 1],
    [230, 135, 30, 1]
]

df = pd.DataFrame(df, columns=['exam1', 'exam2', 'hours_study', 'admitted'])


In [46]:
print(df.head())

   exam1  exam2  hours_study  admitted
0     35     40            5         0
1     42     50            6         0
2     50     52            7         0
3     60     65            8         0
4     67     70            9         1


In [47]:
print(df.shape)

(20, 4)


In [48]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [49]:
print(X.head())

   exam1  exam2  hours_study
0     35     40            5
1     42     50            6
2     50     52            7
3     60     65            8
4     67     70            9


In [50]:
print(y.head())

0    0
1    0
2    0
3    0
4    1
Name: admitted, dtype: int64


In [53]:
mean_vals = X.mean()
min_vals = X.min()
max_vals = X.max()
std_vals = X.std(ddof=1)

In [54]:
for i in range(3):
    print(f"{min_vals[i]:.2f} {max_vals[i]:.2f} {mean_vals[i]:.2f} {std_vals[i]:.2f}")

35.00 230.00 115.45 56.65
40.00 135.00 94.80 28.67
5.00 30.00 16.55 7.67


C:\Users\manis\AppData\Local\Temp\ipykernel_1012\2940200990.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"{min_vals[i]:.2f} {max_vals[i]:.2f} {mean_vals[i]:.2f} {std_vals[i]:.2f}")


In [55]:
std_vals = X.std(ddof=0)

In [56]:
X_std = (X - mean_vals) / std_vals

In [57]:
print(X_std.head())

      exam1     exam2  hours_study
0 -1.456972 -1.961325    -1.545540
1 -1.330200 -1.603419    -1.411727
2 -1.185317 -1.531838    -1.277914
3 -1.004215 -1.066560    -1.144101
4 -0.877443 -0.887607    -1.010288


In [101]:
X_aug = np.c_[np.ones(X.shape[0]), X_std]

In [102]:
print(X_aug)

[[ 1.         -1.45697156 -1.96132514 -1.54553952]
 [ 1.         -1.33019964 -1.60341909 -1.41172658]
 [ 1.         -1.18531745 -1.53183788 -1.27791363]
 [ 1.         -1.00421471 -1.06656002 -1.14410069]
 [ 1.         -0.87744279 -0.887607   -1.01028774]
 [ 1.         -0.73256059 -0.60128216 -0.8764748 ]
 [ 1.         -0.64200922 -0.35074793 -0.6088489 ]
 [ 1.         -0.46090648 -0.24337611 -0.34122301]
 [ 1.         -0.37035511 -0.1717949  -0.20741007]
 [ 1.         -0.27980374 -0.10021369 -0.07359712]
 [ 1.         -0.09870099  0.18611114  0.06021583]
 [ 1.          0.08240175  0.36506417  0.19402877]
 [ 1.          0.26350449  0.54401719  0.32784172]
 [ 1.          0.44460723  0.72297022  0.46165466]
 [ 1.          0.62570998  0.83034203  0.72928055]
 [ 1.          0.80681272  0.90192324  0.99690645]
 [ 1.          1.07846683  1.08087626  1.13071939]
 [ 1.          1.35012094  1.18824808  1.26453234]
 [ 1.          1.71232643  1.25982929  1.53215823]
 [ 1.          2.07453191  1.43

In [103]:
y.shape

(20,)

In [104]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [105]:
def loss(X, y, theta):
    y_cap = sigmoid(X.dot(theta))
    ep = 1e-5
    loss = (-1/n) * (y.dot(np.log(y_cap + ep)) + (1 - y).dot(np.log(1 - y_cap + ep)))
    return loss

In [106]:
print(n)

20


In [107]:
def gradient_descent(X, y, alpha=0.01, epochs=1500):
    theta = np.zeros(X.shape[1])
    for epoch in range(epochs):
        h = sigmoid(X.dot(theta))
        gradient = (1 / n) * (X.T.dot(h - y))
        theta -= alpha * gradient
    return theta

In [108]:
theta = gradient_descent(X_aug, y)
final_loss = loss(X_aug, y, theta)

In [110]:
t_final = np.round(theta.flatten(), 2)

In [111]:
print(f"Final theta: {list(t_final)}")
print(f"Final loss: {round(final_loss, 2)} \n\n")

Final theta: [1.86, 0.45, 1.06, 0.61]
Final loss: 0.2 




In [ ]:
def predict(X):
    X_std = (X - mean_vals) / std_vals
    X_aug = np.c_[np.ones(X_std.shape[0]), X_std]
    p = sigmoid(X_aug.dot(theta))
    return p

In [116]:
new = pd.DataFrame([[72, 80, 11], [150, 118, 20]], columns=['exam1', 'exam2', 'hours_study'])
new_norm = (new - mean_vals) / (std_vals)
new_aug = np.c_[np.ones(new_norm.shape[0]), new_norm]

In [123]:

pred = new_aug.dot(theta)
pred = sigmoid(pred)

for price in pred:
    print(round(price, 2))

0.62
0.96
