# Univariate Linear Regression

In [1]:
import numpy as np
import pandas as pd

C:\Users\manis\AppData\Local\Temp\ipykernel_5304\1662815981.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
data = [
    [35.0, 179.0],
    [42.0, 200.0],
    [50.0, 221.0],
    [60.0, 263.0],
    [67.0, 280.0],
    [75.0, 314.0],
    [80.0, 327.0],
    [90.0, 360.0],
    [95.0, 377.0],
    [100.0, 391.0],
    [110.0, 425.0],
    [120.0, 462.0],
    [130.0, 493.0],
    [140.0, 521.0],
    [150.0, 552.0],
    [160.0, 582.0],
    [175.0, 631.0],
    [190.0, 675.0],
    [210.0, 740.0],
    [230.0, 804.0],
]


In [3]:
df = pd.DataFrame(data, columns=['feature', 'target'])

In [4]:
df.head()

feature  target
0     35.0   179.0
1     42.0   200.0
2     50.0   221.0
3     60.0   263.0
4     67.0   280.0

In [5]:
print(df.shape)

(20, 2)


In [6]:
mean_val = df.iloc[:, 0].mean()
print(mean_val)
std_val = round(df.iloc[:, 0].std(ddof=0), 2)
print(std_val)
print(df.iloc[:, 0].min())
print(df.iloc[:, 0].max())

115.45
55.22
35.0
230.0


In [7]:
X = df.iloc[:, 0]
y = df.iloc[:, 1]

In [8]:
X_norm = (X - X.mean()) / (X.std(ddof=0))

## Gradient Descent

In [9]:
theta0 = 0
theta1 = 0
alpha = 0.01
epochs = 1000
n = len(df)

In [10]:
for i in range(epochs):
    y_hat = theta0 + (theta1 * X_norm)

    gtheta0 = (y_hat - y).sum() / n
    gtheta1 = ((y_hat - y) * X_norm).sum()/ n

    theta0 -= alpha * gtheta0
    theta1 -= alpha * gtheta1

print(theta0, theta1)


439.83101112682647 177.29315298210062


In [11]:
y_cap = theta0 + (theta1 * X_norm)

In [12]:
mse = ((y_cap - y) ** 2).sum() / (2 * n)

In [13]:
print(f"Final theta0={theta0:.3f} | theta1={theta1:.3f} | Final MSE={mse:.2f}")

Final theta0=439.831 | theta1=177.293 | Final MSE=7.58


In [14]:

X_new = np.array([150, 200])
X_new_norm = (X_new - X.mean()) / (X.std(ddof=0))
# X_new_norm = (X_new - mean_val) / std_val
pred = theta0 + theta1 * X_new_norm

for p in pred:
    print(f"{p:.2f}")

550.77
711.31


# Multivariate Linear Regression

In [15]:
import pandas as pd
import numpy as np

In [118]:
df = [
    [35.0, 1.0, 20.0, 179.0],
    [42.0, 2.0, 15.0, 200.0],
    [50.0, 2.0, 18.0, 221.0],
    [60.0, 3.0, 10.0, 263.0],
    [67.0, 3.0, 8.0, 280.0],
    [75.0, 3.0, 12.0, 314.0],
    [80.0, 4.0, 5.0, 327.0],
    [90.0, 4.0, 5.0, 360.0],
    [95.0, 4.0, 6.0, 377.0],
    [100.0, 5.0, 5.0, 391.0],
    [110.0, 5.0, 3.0, 425.0],
    [120.0, 5.0, 2.0, 462.0],
    [130.0, 6.0, 2.0, 493.0],
    [140.0, 6.0, 1.0, 521.0],
    [150.0, 6.0, 1.0, 552.0],
    [160.0, 7.0, 1.0, 582.0],
    [175.0, 7.0, 2.0, 631.0],
    [190.0, 8.0, 2.0, 675.0],
    [210.0, 8.0, 1.0, 740.0],
    [230.0, 9.0, 1.0, 804.0]
]


In [119]:
df = pd.DataFrame(df, columns=['size', 'rooms', 'age', 'price'])

In [120]:
print(df.head())

   size  rooms   age  price
0  35.0    1.0  20.0  179.0
1  42.0    2.0  15.0  200.0
2  50.0    2.0  18.0  221.0
3  60.0    3.0  10.0  263.0
4  67.0    3.0   8.0  280.0


In [121]:
print(df.shape)

(20, 4)


In [122]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [123]:
mean_vals = X.mean(axis=0)
std_vals = X.std(axis=0, ddof=0)
min_vals = X.min(axis=0)
max_vals = X.max(axis=0)

In [124]:
n = len(df)
cols = df.shape[1]

In [125]:
for i in range(cols - 1):
    print(f"{mean_vals[i]:.2f} {std_vals[i]:.2f} {min_vals[i]:.2f} {max_vals[i]:.2f}")

115.45 55.22 35.00 230.00
4.90 2.17 1.00 9.00
6.00 5.82 1.00 20.00


C:\Users\manis\AppData\Local\Temp\ipykernel_5304\3673449494.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"{mean_vals[i]:.2f} {std_vals[i]:.2f} {min_vals[i]:.2f} {max_vals[i]:.2f}")


In [126]:
X_norm = (X - mean_vals) / (std_vals)

In [127]:
print(X_norm.head())

       size     rooms       age
0 -1.456972 -1.800853  2.404519
1 -1.330200 -1.339096  1.545762
2 -1.185317 -1.339096  2.061016
3 -1.004215 -0.877338  0.687005
4 -0.877443 -0.877338  0.343503


In [128]:
X_aug = np.c_[np.ones(X_norm.shape[0]), X_norm]

In [129]:
def gradientDescent(X, y, alpha, epochs):
    theta = np.zeros(X.shape[1])
    # n is defined earlier
    for i in range(epochs):
        pred = X.dot(theta)
        grad = (X.T.dot(pred - y)) / (n)
        theta -= alpha * grad
    return theta



In [130]:
alpha = 0.01
epochs = 300

In [131]:
theta = gradientDescent(X_aug, y, alpha, epochs)
print(theta)

[418.27936274  82.59776628  69.70922778 -25.24441416]


In [132]:
theta_normal = np.linalg.inv(X_aug.T.dot(X_aug)).dot(X_aug.T).dot(y)

In [133]:
def mse(X, y, theta):
    y_cap = X.dot(theta)
    mse = np.sum((y_cap - y) ** 2) / (2 * n)

    return mse

In [134]:
mse_gd = mse(X_aug, y, theta)
print(theta)
mse_normal = mse(X_aug, y, theta_normal)

[418.27936274  82.59776628  69.70922778 -25.24441416]


In [135]:
print(f"Final theta=[{', '.join(f'{x:.3f}' for x in theta)}]")
print(f"Final MSE={round(mse_gd, 2)}")
print(f"MSE Difference={round(abs(mse_gd - mse_normal), 5)}")

Final theta=[418.279, 82.598, 69.709, -25.244]
Final MSE=507.47
MSE Difference=503.76598


In [144]:
print(theta)

[418.27936274  82.59776628  69.70922778 -25.24441416]


In [153]:
new = pd.DataFrame([[150, 3, 5], [200, 4, 2]], columns=['size', 'rooms', 'age'])
new_norm = (new - mean_vals) / (std_vals)
new_aug = np.c_[np.ones(new_norm.shape[0]), new_norm]

In [155]:
pred_gd = new_aug.dot(theta)

for price in pred_gd:
    print(round(price, 2))

413.14
533.13
